CREATE TABLE jobs (
    date DATE NOT NULL,
    companyId TEXT,
    jobId TEXT,
    country CHAR(2) NOT NULL,
    stateProvince CHAR(2) NOT NULL,
    city TEXT NOT NULL,
    avgOverallRating FLOAT NOT NULL,
    numReviews INTEGER,
    industry TEXT,
    normTitle TEXT,
    normTitleCategory TEXT,
    descriptionCharacterLength INTEGER NOT NULL,
    descriptionWordCount INTEGER NOT NULL,
    experienceRequired INTEGER NOT NULL,
    estimatedSalary INTEGER,
    salaryCurrency TEXT,
    jobLanguage TEXT NOT NULL,
    supervisingJob INTEGER NOT NULL,
    licenseRequiredJob INTEGER NOT NULL,
    educationRequirements TEXT,
    jobAgeDays INTEGER NOT NULL,
    clicks INTEGER NOT NULL,
    localClicks INTEGER NOT NULL,
    id INTEGER PRIMARY KEY AUTOINCREMENT
)
